### ISSUE TITLE
EPIC: Improve testing and documentation infrastructure

### ISSUE THREAD

**Issue by kallimachos** [rueckstiess/mtools#542]
mtools could benefit from a more versatile testing framework, a standardized coding style, and more accessible documentation. To achieve these goals, I suggest using the following tools:

#### tox
- [tox](https://tox.readthedocs.io/en/latest/) provides automated, standardized testing.
- makes testing against multiple Python versions straightforward, which is a prerequisite for completing #527
- enables test environments for multiple targets (docs, coding style, nosetests)
- enables easy integration of tests and documentation builds with Travis

#### flake8
- [flake8](http://flake8.pycqa.org/en/latest/) includes lint checks provided by the PyFlakes project, PEP8 inspired style checks provided by the PyCodeStyle project, and McCabe complexity checking provided by the McCabe project
- extensible through plugins

#### isort
- [isort](https://readthedocs.org/projects/isort/) checks for standardized import order and style

#### pep257
- [pep257](https://pypi.python.org/pypi/pep257) checks that code complies with the docstring conventions suggested in PEP257

#### Sphinx
- [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html) is the de facto standard for creating Python documentation with reStructuredText
- integrates cleanly with tox
- style is enforced with doc8
- spelling is checked with sphinxcontrib-spelling
- built documentation can be automatically deployed by Travis to a gh-page

### Implementation steps

- [x] enable tox
  - remove current test lines from setup.py
  - add tox.ini
  - add test-requirements.txt
  - add coverage report
  - add flake8 with pep8-naming, isort, and pep257 as testenvs
  - update .travis.yml
- [x] fix errors found by flake8
- [x] fix errors found by isort
- [x] fix errors found by pep257
- [ ] add flake8, isort, pep257 to full test run
- [x] add RST documentation project with tests
  - include all content from current wiki pages
  - enhance section on contributing (update how to run tests)
  - add section on coding standards
- [ ] add Travis gh-pages deploy script for documentation
- [x] update `README.rst` and repository landing page with links to gh-pages documentation
- [x] remove wiki pages
